export const CONFIG = {
    ANALYZING_CA: '2oV3kugT2EDm6xzgJ9BVERzxLf4bSYYtFPH25isJpump',
    TOP_HOLDERS: 50,
    MIN_HOLDING_USD: 1_000,
    MIN_HOLDING_USD_OTHER_TOKEN: 1_000,
    MIN_MARKET_CAP_USD_OTHER_TOKEN: 100_000,
    MIN_HOLDERS_COUNT_TO_CHART: 3,
    EXCLUDED_ADDRESSES: new Set(['5Q544fKrFoe6tsEbD7S8EmxGTJYAKtTVhAW5Q5pge4j1']),
    RESEARCH_FOLDER: 'research',
};
